### ISSUE TITLE
create static site generator for bechamel with sample webpack config

### ISSUE THREAD

**Issue by elyseholladay** [RetailMeNotSandbox/bechamel#16]
As @lzilioli works on https://github.com/RetailMeNotSandbox/roux/issues/21, we can work on the static site generator part. Bechamel will become a static site gen using https://github.com/markdalgleish/static-site-generator-webpack-plugin that uses the webpack config specified to render out HTML pages w/ the Bechamel chrome + an iframe that loads in each ingredient, its rendered preview and JS.

**Comment by lzilioli** [comment]
There are a few issues/unanswered questions with this approach, and I am not confident that trading the cost of maintaining the express preview code with the cost of answering the questions is going to be worthwhile.

1. multiple model variations - how do we render them? Do we render out different static previews for each model variation, or do we render a single preview that comes with some JS code to listen for clicks on different model variations and re-renders the new preview live on the page
2. triggering the sass build - the static-site-generator plugin requires that you can statically list all of your dependencies that result in the final static site. This means that we need a file that statically require's the ingredient's sass entrypoint, javascript, and handlebars template. This file would be the file whose default export is a method that returns a string of the rendered html preview for the ingredient. I think we can achieve this by taking two passes thru the static-site-generator plugin, one that generates an 'index.js' for each ingredient which we then pass to the second pass of the generator plugin to get the preview.
3. the preview template - all of the logic for choosing and rendering out the right preview.hbs currently lives in the preview middleware. This would need to be moved *somewhere* and the right somewhere is probably to have the default preview template specified on a per-pantry basis.

Once the above is complete, we would need to make more passes with the static-site plugin to render out the app chrome.

Not sure taking on the work for (1), (2), and (3) is less than or more maintainable than moving forward with the expressjs approach we are currently using.

**Comment by knksmith57** [comment]
Capturing some f2f chat chit here for posterity:

> 1. multiple model variations ...

The "glue" piece is TBD, but the algo is simple enough:
1. get an initialized pantry instance (eg: via `pantry.resolve()` or similar)
2. `_.filter(pantry.ingredients, i => i.entryPoints.model)`
3. for each model, render preview for ingredient with that model

> 2. triggering the sass build ...

There are a few ways to do this, but the simplest may be to compile all ingredient `sass` entrypoints _first_, dumping them to disk in a known file structure, and _then_ triggering the static site generator so that it is only responsible for assembling the files and rendering the html.

We could then trigger the static site generation on changes to the files on disk.

> 3. the preview template ...

Yep, that will either need to be refactored to simply expose the piece that renders the preview html _outside_ of express middleware, or carved out into a new package altogether.

All things considered, this work may change the priority of reworking bechamel into a static site. That's for y'all to decide, but I'm always happy to pitch in my $0.02 :)

**Comment by lzilioli** [comment]
Thanks, @knksmith57. I agree this baloons scope outside of what we want to take on right now. I think sticking with the express server approach is preferred for the time bing.

@elyseholladay I'll leave it up to you if you wanna close this ticket or keep it open, but it sounds like we are aligned on changing gears back to doing work to get the existing express version of the app off the ground and ready to be open sourced.

**Comment by elyseholladay** [comment]
closing anticipating the OS release of static-bechamel
